logging:
  level:
    org.springframework.cloud.netflix.eureka.server: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: securty-oauth2
            client-secret: MYPOUP5nGAGRSWsCHEPCABiqRwmjvHun
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/oauth2/code/keycloak"
            scope: openid, message.read
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/keyclock
